name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make test
      run: make test
      working-directory: test
    - name: make stylecheck
      run: make stylecheck
      working-directory: test
    - name: make formatcheck
      run: make formatcheck
      working-directory: test
    - name: make clean
      run: make clean
      working-directory: test
